targets:
  $default:
    builders:
      source_gen:combining_builder:
        generate_for:
          exclude:
            - test
          include:
            - 'lib/**/*.b.dart'

      mek_data_class_generator|data_class:
        enabled: true
        options:
          page_width: 100
        generate_for:
          exclude:
            - test
          include:
            - 'lib/**/*.b.dart'
