name: kuama_permissions
description: A starting point for Dart libraries or applications.
publish_to: 'none'
version: 1.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

scripts:
  # To generate .g files:
  build:watch: dart run build_runner watch --delete-conflicting-outputs
  # To generate library file
  build:index: dart pub global run index_generator

dependencies:
  flutter:
    sdk: flutter

  kuama_core:
    git:
      url: https://github.com/Kuama-IT/kuama_dart.git
      path: kuama_core
      ref: 1.1.0

  permission_handler_platform_interface: ^3.12.0
  permission_handler: ^11.0.1
  shared_preferences: ^2.1.0

  meta: # Version defined in kuama_core
  get_it: # Version defined in kuama_core
  rxdart: ^0.27.7
  collection: ^1.17.0
  bloc: ^8.1.1
  bloc_concurrency: ^0.2.1

  mek_data_class: ^1.4.0

dev_dependencies:
  mek_lints: ^1.0.0

  flutter_test:
    sdk: flutter

  mocktail: ^0.3.0

  build_runner: ^2.4.6
  mek_data_class_generator: ^1.5.1

dependency_overrides:
  kuama_core:
    path: ../kuama_core

index_generator:
  page_width: 100
  exclude:
    # Ignore all generated dart files
    - '**.g.dart'
    # Ignore all private folders or files
    - '{_,**/_}*{/**,.dart}'
  indexes:
    - path: lib
      name: kuama_permissions
      exports:
        - package: package:permission_handler/permission_handler.dart
          show:
            - Permission
            - PermissionStatus
            - PermissionStatusGetters
