name: kuama_permissions
description: A starting point for Dart libraries or applications.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=2.16.0 <3.0.0'
  flutter: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  kuama_core:
    path: ../kuama_core

  permission_handler: ^9.2.0
  shared_preferences: ^2.0.13

  meta: # Version defined in kuama_core
  get_it: # Version defined in kuama_core
  pure_extensions: ^4.1.1
  bloc: ^8.0.3
  bloc_concurrency: ^0.2.0

  mek_data_class: ^0.1.0

dev_dependencies:
  mek_lints: ^0.2.0

  flutter_test:
    sdk: flutter

  mocktail: ^0.3.0

  # To generate .g files:
  # flutter packages pub run build_runner build --delete-conflicting-outputs
  # flutter packages pub run build_runner watch --delete-conflicting-outputs
  build_runner: ^2.1.8
  mek_data_class_generator: ^0.1.1

dependency_overrides:
  test_api: 0.4.9

index_generator:
  page_width: 100
  exclude:
    # Ignore all generated dart files
    - '**.g.dart'
    # Ignore all private folders or files
    - '{_,**/_}*{/**,.dart}'
  indexes:
    - path: lib
      name: kuama_permissions
      exports:
        - package: package:permission_handler/permission_handler.dart
          show:
            - Permission
            - PermissionStatus
            - PermissionStatusGetters
