name: kuama_core
description: A starting point for Dart libraries or applications.
publish_to: 'none'
version: 0.2.3

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  kuama_flutter:
    git:
      url: https://github.com/Kuama-IT/kuama_flutter.git
      ref: develop

  get_it: ^7.2.0 # Global packages version

dev_dependencies:
  mek_lints: ^0.3.0

  test: ^1.21.1
