name: kuama_core
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  get_it: ^7.2.0 # Global packages version

dev_dependencies:
  mek_lints: ^0.2.0

  test: ^1.16.0
