name: kuama_position
description: A new Flutter project.
publish_to: 'none'
version: 0.3.0

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  kuama_core:
    git:
      url: https://github.com/Kuama-IT/kuama_dart.git
      path: kuama_core
      ref: 0.3.0
  kuama_permissions:
    git:
      url: https://github.com/Kuama-IT/kuama_dart.git
      path: kuama_permissions
      ref: 0.3.0


  geolocator_platform_interface: ^4.0.5
  geolocator: ^9.0.0

  get_it: # Version defined in kuama_core
  rxdart: ^0.27.4
  pure_extensions: ^4.2.0
  bloc: ^8.0.3
  bloc_concurrency: ^0.2.0
  equatable: ^2.0.3

dependency_overrides:
  kuama_core:
    path: ../kuama_core
  kuama_permissions:
    path: ../kuama_permissions

dev_dependencies:
  mek_lints: ^0.3.0

  flutter_test:
    sdk: flutter

  mocktail: ^0.3.0

flutter:

index_generator:
  page_width: 100
  exclude:
    # Ignore all generated dart files
    - '**.g.dart'
    # Ignore all private folders or files
    - '{_,**/_}*{/**,.dart}'
  indexes:
    - path: lib
      name: kuama_position
