name: kuama_position
description: A new Flutter project.
publish_to: 'none'
version: 1.0.1

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=3.3.0"

scripts:
  # To generate library file
  build:index: dart pub global run index_generator

dependencies:
  flutter:
    sdk: flutter

  kuama_core:
    git:
      url: https://github.com/Kuama-IT/kuama_dart.git
      path: kuama_core
      ref: 1.0.1
  kuama_permissions:
    git:
      url: https://github.com/Kuama-IT/kuama_dart.git
      path: kuama_permissions
      ref: 1.0.1


  geolocator_platform_interface: ^4.0.7
  geolocator: ^9.0.2

  get_it: # Version defined in kuama_core
  rxdart: ^0.27.7
  pure_extensions: ^5.0.0
  bloc: ^8.1.1
  bloc_concurrency: ^0.2.1
  equatable: ^2.0.5

dependency_overrides:
  kuama_core:
    path: ../kuama_core
  kuama_permissions:
    path: ../kuama_permissions

dev_dependencies:
  mek_lints: ^1.0.0

  flutter_test:
    sdk: flutter

  mocktail: ^0.3.0

flutter:

index_generator:
  page_width: 100
  exclude:
    # Ignore all generated dart files
    - '**.g.dart'
    # Ignore all private folders or files
    - '{_,**/_}*{/**,.dart}'
  indexes:
    - path: lib
      name: kuama_position
