name: Analyze and test code

on:
  pull_request:
  push:
    branches:
      # Run test, analyze and coverage generation also when the PR gets merged into develop
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  analyze-and-test:
    # The type of machine to run the job on. [windows,macos, ubuntu , self-hosted]
    runs-on: ubuntu-latest
    # Sequence of tasks called
    steps:
      # The branch or tag ref that triggered the workflow will be checked out.
      - uses: actions/checkout@v3
      # Setup a flutter environment.
      # https://github.com/marketplace/actions/flutter-action
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.x'
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:'

      # Install melos
      - name: Install global melos dependency
        run: dart pub global activate melos

      # Resolve dependencies
      - name: Resolve dependencies
        timeout-minutes: 2
        run: melos run get

      # Analysis code
      - name: Check the format of the code
        run: melos run format
      - name: Analyze the code
        run: melos run analyze

      # Run flutter widgets tests and unit tests
      - name: Test the code
        run: melos run test --no-select